const data = [
  {
    id: 1,
    name: "REXA",
    type: "Ecommerce Website",
    git: "https://github.com/EmmanuelisongDev/Rexa",
    link: "https://rexa-ecommerce.netlify.app/",
    image: require("./assets/rexa.png"),
    tools: ["React", "TailwindCSS", "SanityCMS", "Paystack"],
  },
  {
    id: 2,
    name: "CokBok.",
    type: "Food Recipe App",
    git: "https://github.com/EmmanuelisongDev/CokBok",
    link: "https://cok-bok.netlify.app/",
    image: require("./assets/cokbok.png"),
    tools: ["React", "TailwindCSS", "SpoonacularApi"],
  },
  {
    id: 3,
    name: "Tetris",
    type: "Retro Game",
    git: "https://github.com/EmmanuelisongDev/Tetris",
    link: "https://tetris-projectv.netlify.app/",
    image: require("./assets/tetris.png"),
    tools: ["HTML", "CSS", "Javascript"],
  },
  {
    id: 4,
    name: "DailyBread",
    type: "Landing Page",
    git: "https://github.com/EmmanuelisongDev/DailyBread",
    link: "https://daily-bread-emma.netlify.app/",
    image: require("./assets/dailybread.png"),
    tools: ["React", "TailwindCSS"],
  },
  {
    id: 5,
    name: "Planetor",
    type: "Planet Calculator",
    git: "https://github.com/EmmanuelisongDev/Planetorz.git",
    link: "https://planetor.netlify.app/",
    image: require("./assets/planet.png"),
    tools: ["HTML", "CSS", "Javascript"],
  },
  {
    id: 6,
    name: "WeatherMan",
    type: "Weather Application",
    git: "https://github.com/EmmanuelisongDev/WeatherMan",
    link: "https://weatherman-emma.netlify.app",
    image: require("./assets/weather.png"),
    tools: ["React", "TailwindCSS", "Open Weather Map"],
  },
];

export default data;
